
server:
  port: 8080


spring:
      data:
           mongodb:
             uri: mongodb://root-user-123:root-user-123@@mongodb-service:27017
             database: microservices

      application:
        name: RATING-SERVICE


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8080/eureka

okta:
  oauth2:
    issuer: https://dev-34423417.okta.com/oauth2/default
    audience: api://default